# Generated by Django 4.1.5 on 2023-02-06 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("promocao", "0002_promocao_supermercados"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="promocao",
            name="produtos",
        ),
    ]
