# Generated by Django 4.1.5 on 2023-02-04 03:20

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="username",
            field=models.CharField(
                help_text="Um nome curto que será usado para identificalo",
                max_length=30,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[\\w.@+-]+$"),
                        "Informe um nome de usuário válido. Este valor deve conter apenas letras, números e os caracteres: @/./+/-/_ .",
                        "invalid",
                    )
                ],
                verbose_name="Usuário",
            ),
        ),
    ]
