# Generated by Django 4.1.5 on 2023-01-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Supermercado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "imagem",
                    models.ImageField(
                        upload_to="supermercado/supermercados/", verbose_name="Imagem"
                    ),
                ),
                ("cpf", models.CharField(max_length=11, verbose_name="CPF")),
                ("cnpj", models.CharField(max_length=14, verbose_name="CNPJ")),
                ("cep", models.CharField(max_length=11, verbose_name="CEP")),
                ("cidade", models.CharField(max_length=100, verbose_name="Cidade")),
                ("bairro", models.CharField(max_length=11, verbose_name="Bairro")),
                ("rua", models.CharField(max_length=100, verbose_name="Rua")),
                ("numero", models.IntegerField(verbose_name="Número")),
                (
                    "date_joined",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Entrada"
                    ),
                ),
            ],
            options={
                "verbose_name": "Supercado",
                "verbose_name_plural": "Supermercado",
            },
        ),
    ]
