# Generated by Django 4.1.5 on 2023-01-20 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supermercado", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="supermercado",
            options={
                "verbose_name": "Supermercado",
                "verbose_name_plural": "Supermercados",
            },
        ),
    ]
