# Generated by Django 4.1.5 on 2023-01-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supermercado", "0003_supermercado_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supermercado",
            name="imagem",
            field=models.ImageField(
                null=True,
                upload_to="supermercado/supermercados/",
                verbose_name="Imagem",
            ),
        ),
    ]
