# Generated by Django 4.1.5 on 2023-01-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Categoria")),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Produto")),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Valor"
                    ),
                ),
                ("estoque", models.IntegerField(verbose_name="Estoque")),
                (
                    "imagem",
                    models.ImageField(
                        upload_to="produto/produtos/", verbose_name="Imagem"
                    ),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "criado",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "modificado",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado em"),
                ),
                (
                    "categorias",
                    models.ManyToManyField(
                        blank=True, to="produto.categoria", verbose_name="Categorias"
                    ),
                ),
            ],
            options={
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
                "ordering": ["nome"],
            },
        ),
    ]
