# Generated by Django 4.1.4 on 2023-01-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produto", "0002_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="categorias",
            field=models.ManyToManyField(
                blank=True, to="produto.categoria", verbose_name="Categorias"
            ),
        ),
    ]
