# Generated by Django 4.1.5 on 2023-02-04 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("supermercado", "0004_alter_supermercado_imagem"),
        ("produto", "0002_produto_supermercados"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="supermercados",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="supermercado.supermercado",
            ),
        ),
    ]
